DROP TABLE IF EXISTS nosliw.MINIAPP_USER;
DROP TABLE IF EXISTS nosliw.MINIAPP_GROUP;
DROP TABLE IF EXISTS nosliw.MINIAPP_USERGROUP;
DROP TABLE IF EXISTS nosliw.MINIAPP_USERAPP;
DROP TABLE IF EXISTS nosliw.MINIAPP_APPINSTANCE;
DROP TABLE IF EXISTS nosliw.MINIAPP_APPINSTANCESETTING;
DROP TABLE IF EXISTS nosliw.MINIAPP_APPINSTANCERESULT;

CREATE TABLE nosliw.MINIAPP_USER(
	ID   				VARCHAR(20)			NOT NULL ,
	NAME				VARCHAR(20)			NOT NULL,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_GROUP(
	ID   				VARCHAR(20)			NOT NULL ,
	NAME				VARCHAR(20)			NOT NULL,
	PARENTGROUP			VARCHAR(20)			,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_USERGROUP(
	ID   				VARCHAR(20)			NOT NULL ,
	USERID				VARCHAR(20)			NOT NULL,
	GROUPID				VARCHAR(20)			NOT NULL,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_USERAPP(
	ID   				VARCHAR(20)			NOT NULL ,
	USERID 				VARCHAR(20)			NOT NULL ,
	APPID 				VARCHAR(20)			NOT NULL ,
	APPNAME				VARCHAR(20)			NOT NULL ,
	APPINSTANCEID		VARCHAR(20)			,
	GROUPID 			VARCHAR(20)			,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_APPINSTANCE(
	ID   				VARCHAR(20)			NOT NULL ,
	APPID		VARCHAR(20)			NOT NULL ,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_APPINSTANCESETTING(
	ID   				VARCHAR(20)			NOT NULL ,
	SETTING 				VARCHAR(20)			NOT NULL ,
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.MINIAPP_APPINSTANCERESULT(
	ID   				VARCHAR(20)			NOT NULL ,
	SETTINGID 				VARCHAR(20)			NOT NULL ,
	
	PRIMARY KEY (ID)	
);
