{
   "id":"service_test_listoutput",
   "name":"service_test_listoutput",
   "displayName":"service_test_listoutput",
   "description":"test service with list output",
   "tag":[
      "test",
      "list",
      "output"
   ],
   "interface":{
      "parm":[
         {
            "name":"parm1",
            "displayName":"Parm1",
            "description":"Parm1",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            },
            "defaultValue":{
               "dataTypeId":"test.string;1.0.0",
               "value":"Parm1"
            }
         },
         {
            "name":"parm2",
            "displayName":"Parm2",
            "description":"Parm2",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         },
         {
            "name":"parm3",
            "displayName":"Parm3",
            "description":"Parm3",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         },
         {
            "name":"parm4",
            "displayName":"Parm4",
            "description":"Parm4",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         },
         {
            "name":"parm5",
            "displayName":"Parm5",
            "description":"Parm5",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         },
         {
            "name":"parm6",
            "displayName":"Parm6",
            "description":"Parm6",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         },
         {
            "name":"parm7",
            "displayName":"Parm7",
            "description":"Parm7",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            }
         }
      ],
      "result":{
         "success":{
            "output":[
               {
                  "name":"simpleOutput1",
                  "displayName":"SimpleOutput1",
                  "dataInfo":{
                     "criteria":"test.string;1.0.0"
                  }
               },
               {
                  "name":"simpleOutput2",
                  "displayName":"SimpleOutput2",
                  "dataInfo":{
                     "criteria":"test.string;1.0.0"
                  }
               }
            ]
         }
      }
   }
}