{
   "id":"service_test_listoutput",
   "name":"service_test_listoutput",
   "displayName":"service_test_listoutput",
   "description":"test service with list output",
   "tag":[
      "test",
      "list",
      "output"
   ],
   "interface":{
      "request":[
         {
            "name":"parm1",
            "displayName":"Parm1",
            "description":"Parm1",
            "dataInfo":{
               "criteria":"test.string;1.0.0"
            },
            "defaultValue":{
               "dataTypeId":"test.string;1.0.0",
               "value":"Parm1"
            }
         },
         {
            "name":"parm2",
            "displayName":"Parm2",
            "description":"Parm2",
            "dataInfo":{
               "criteria":"test.float;1.0.0"
            }
         }
      ],
      "result":{
         "success":{
            "output":[
               {
                  "name":"listOutput",
                  "displayName":"ListOutput",
                  "criteria":"test.array;1.0.0%%||element:test.map;1.0.0%%||attribute1:test.string;1.0.0,attribute2:test.float;1.0.0,attribute3:test.float;1.0.0||%%||%%"
               }
            ]
         }
      }
   }
}