
if(typeof nosliw!='undefined' && nosliw.runtime!=undefined && nosliw.runtime.getResourceService()!=undefined) nosliw.runtime.getResourceService().importResource({"id":{"id":"Example_Object_Test",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Example_Object_Test",
"type":"resource",
"context":{"local2Global":{"business":"business___public"
},
"context":{"element":{"business___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"node",
"processed":"true",
"child":{"a":{"type":"node",
"processed":"true",
"child":{"aa":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
},
"defaultValue":{"a":{"aa":{"dataTypeId":"test.string;1.0.0","value":"This is my world!"},"cc":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}],"ee":{"dataTypeId":"test.array;1.0.0","value":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}]}}}
},
"business":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"self",
"definition":{"type":"node",
"processed":"true",
"child":{"a":{"type":"node",
"processed":"true",
"child":{"aa":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
},
"defaultValue":{"a":{"aa":{"dataTypeId":"test.string;1.0.0","value":"This is my world!"},"cc":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}],"ee":{"dataTypeId":"test.array;1.0.0","value":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}]}}}
}
}
}
},
"elementEvents":[{"uiId":"672",
"event":"click",
"function":"newElementInLoop"
}],
"tagEvents":[],
"attributes":{},
"html":"&lt;!--		&lt;nosliw-varviewer/&gt;  --&gt; &lt;br nosliwid=&quot;670&quot;&gt; &lt;br nosliwid=&quot;671&quot;&gt;&lt;a href=&quot;&quot; nosliwid=&quot;672&quot;&gt;&lt;span&gt;New&lt;/span&gt;&lt;/a&gt;&lt;br nosliwid=&quot;673&quot;&gt; &lt;br nosliwid=&quot;674&quot;&gt; &lt;br nosliwid=&quot;675&quot;&gt; &lt;!--	Content:&lt;%=?(business.a.aa)?.value + '   6666 ' %&gt; --&gt; &lt;br nosliwid=&quot;676&quot;&gt;&lt;span&gt; TextInput:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;677-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;677-tag-end&quot;&gt;&lt;/nosliw&gt;   &lt;!-- This part can be used to define context (variable)				it describle data type criteria for each context element and its default value		--&gt;  &lt;!-- This part can be used to define expressions		--&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"677":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Test",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"business.a.aa",
"nosliwid":"677"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"script":{ newElementInLoop : function(data, info, env){ event.preventDefault(); var node_createContextVariable = nosliw.getNodeData("uidata.context.createContextVariable"); var node_CONSTANT = nosliw.getNodeData("constant.CONSTANT"); var node_requestServiceProcessor = nosliw.getNodeData("request.requestServiceProcessor"); var node_createBatchUIDataOperationRequest = nosliw.getNodeData("uidata.uidataoperation.createBatchUIDataOperationRequest"); var node_UIDataOperation = nosliw.getNodeData("uidata.uidataoperation.UIDataOperation"); var node_uiDataOperationServiceUtility = nosliw.getNodeData("uidata.uidataoperation.uiDataOperationServiceUtility"); var node_createContextVariableInfo = nosliw.getNodeData("uidata.context.createContextVariableInfo"); var eleData = { dataTypeId: "test.string;1.0.0", value: "This is my world 33333!" }; var requestInfo = node_createBatchUIDataOperationRequest(this.getContext()); var uiDataOperation = new node_UIDataOperation(node_createContextVariableInfo("business.a.cc"), node_uiDataOperationServiceUtility.createAddElementOperationService("", eleData, 1)); requestInfo.addUIDataOperation(uiDataOperation); node_requestServiceProcessor.processRequest(requestInfo, false); }, textInputValueChanged : function(info, env){ env.trigueEvent("changeInputText", info.eventData); }, command_Start :function(data, env){ return data.data + " Start"; }, }
}, {"loadPattern":"file"
});

