
if(typeof nosliw!='undefined' && nosliw.runtime!=undefined && nosliw.runtime.getResourceService()!=undefined) nosliw.runtime.getResourceService().importResource({"id":{"id":"Example_Object_Basic",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Example_Object_Basic",
"type":"resource",
"context":{"local2Global":{"business":"business___public",
"from":"from___public",
"to":"to___public",
"aaaa":"aaaa___public",
"bbbb":"bbbb___public",
"cccc":"cccc___public",
"dddd":"dddd___public",
"ffff":"ffff___public",
"eeee":"eeee___public",
"base":"base___public",
"element111":"element111___public",
"index":"index___public"
},
"context":{"element":{"business___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"node",
"processed":"true",
"child":{"a":{"type":"node",
"processed":"true",
"child":{"aa":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
},
"defaultValue":{"a":{"aa":{"dataTypeId":"test.string;1.0.0","value":"This is my world!"},"cc":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}],"ee":{"dataTypeId":"test.array;1.0.0","value":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}]}}}
},
"business":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"self",
"definition":{"type":"node",
"processed":"true",
"child":{"a":{"type":"node",
"processed":"true",
"child":{"aa":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
},
"defaultValue":{"a":{"aa":{"dataTypeId":"test.string;1.0.0","value":"This is my world!"},"cc":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}],"ee":{"dataTypeId":"test.array;1.0.0","value":[{"dataTypeId":"test.string;1.0.0","value":"This is my world 1111!"},{"dataTypeId":"test.string;1.0.0","value":"This is my world 2222!"}]}}}
},
"element111___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"defaultValue":{"dataTypeId":"test.string;1.0.0","value":"Include Element!"}
},
"element111":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
},
"defaultValue":{"dataTypeId":"test.string;1.0.0","value":"Include Element!"}
},
"index___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
},
"defaultValue":{"dataTypeId":"test.integer;1.0.0","value":100}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
},
"defaultValue":{"dataTypeId":"test.integer;1.0.0","value":100}
}
}
}
},
"elementEvents":[{"uiId":"743",
"event":"click",
"function":"newElementInLoop"
}],
"tagEvents":[{"uiId":"740",
"event":"valueChanged",
"function":"textInputValueChanged"
}],
"attributes":{},
"html":"&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;730-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;730-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;731-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;731-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;732&quot;&gt;&lt;span&gt; Content:&lt;/span&gt;&lt;span nosliwid=&quot;728&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;733&quot;&gt;&lt;span&gt; Content:&lt;/span&gt;&lt;span nosliwid=&quot;729&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;734&quot;&gt;&lt;span&gt; Attribute:&lt;/span&gt;&lt;span style=&quot;&quot; nosliwid=&quot;735&quot;&gt;&lt;span&gt;Phone Number : &lt;/span&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;736&quot;&gt; &lt;br nosliwid=&quot;737&quot;&gt;&lt;span&gt; TextInput:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;738-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;738-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;739&quot;&gt;&lt;span&gt; TextInput: &lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;740-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;740-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;741&quot;&gt; &lt;br nosliwid=&quot;742&quot;&gt;&lt;a href=&quot;&quot; nosliwid=&quot;743&quot;&gt;&lt;span&gt;New&lt;/span&gt;&lt;/a&gt;&lt;br nosliwid=&quot;744&quot;&gt; &lt;br nosliwid=&quot;745&quot;&gt; &lt;br nosliwid=&quot;746&quot;&gt; &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;747-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;747-tag-end&quot;&gt;&lt;/nosliw&gt;   &lt;!-- This part can be used to define context (variable)				it describle data type criteria for each context element and its default value		--&gt;  &lt;!-- This part can be used to define expressions		--&gt;",
"constants":{"from___public":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
},
"from":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
},
"to___public":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
},
"to":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
},
"aaaa___public":"18",
"aaaa":"18",
"bbbb___public":"true",
"bbbb":"true",
"cccc___public":{"a":12345,"b":true,"c":"good","d":18},
"cccc":{"a":12345,"b":true,"c":"good","d":18},
"dddd___public":"12351.0",
"dddd":"12351.0",
"ffff___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"LITERATE",
"value":"Thisismyworldabcdef"
},
"ffff":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"LITERATE",
"value":"Thisismyworldabcdef"
},
"eeee___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"sismfff"
},
"eeee":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"sismfff"
},
"base___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"This is my world!"
},
"base":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"This is my world!"
}
},
"events":{"changeInputText":{"name":"changeInputText",
"description":"",
"info":{},
"data":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"changeInputTextIncludeBasic":{"name":"changeInputTextIncludeBasic",
"description":"",
"info":{},
"data":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"changeInputTextInclude":{"name":"changeInputTextInclude",
"description":"",
"info":{},
"data":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
}
},
"commands":{"Start":{"name":"Start",
"description":"",
"info":{},
"parm":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
},
"result":"result"
},
"Include":{"name":"Include",
"description":"",
"info":{},
"parm":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
},
"result":"result"
}
},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"#|?(business)?.a.aa.subString(from:&(from)&,to:&(to)&)|#.value + ?(business.a.dd)? + ' 6666 ' ",
"variableNames":["business.a.aa","business.a.dd"],
"expressions":{"0_0":{"operand":{"type":"operation",
"outputCriteria":"test.string;1.0.0",
"operation":"subString",
"dataTypeId":"test.string;1.0.0",
"parms":{"from":{"type":"constant",
"outputCriteria":"test.integer;1.0.0",
"name":"from",
"data":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
}
},
"to":{"type":"constant",
"outputCriteria":"test.integer;1.0.0",
"name":"to",
"data":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
}
},
"base":{"type":"variable",
"outputCriteria":"test.string;1.0.0",
"variableName":"business.a.aa"
}
},
"matchersParms":{"base":{"test.string;1.0.0":{"dataTypeId":"test.string;1.0.0",
"relationship":{"source":"test.string;1.0.0",
"target":"test.string;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
},
"from":{"test.integer;1.0.0":{"dataTypeId":"test.integer;1.0.0",
"relationship":{"source":"test.integer;1.0.0",
"target":"test.integer;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
},
"to":{"test.integer;1.0.0":{"dataTypeId":"test.integer;1.0.0",
"relationship":{"source":"test.integer;1.0.0",
"target":"test.integer;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
}
}
},
"variablesMatchers":{},
"variableInfos":{"business___public.a.aa":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"business___public.a.cc":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
},
"business.a.aa":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"business.a.cc":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
},
"element111___public":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"element111":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"index___public":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
},
"index":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
}
}
},
"uiId":"729",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return expressionsData["0_0"].value + variablesData["business.a.dd"] + ' 6666 ' ;
} 

}
},{"scriptExpressions":{"0":{"definition":"?(business.a.aa)?.value + ' 6666 ' ",
"variableNames":["business.a.aa"],
"expressions":{}
}
},
"uiId":"728",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["business.a.aa"].value + ' 6666 ' ;
} 

}
}],
"scriptExpressionInAttributes":[{"scriptExpressions":{"1":{"definition":"#|?(business)?.a.aa.subString(from:&(from)&,to:&(to)&)|#.value=='s isfff'?'red':'blue'",
"variableNames":["business.a.aa"],
"expressions":{"1_0":{"operand":{"type":"operation",
"outputCriteria":"test.string;1.0.0",
"operation":"subString",
"dataTypeId":"test.string;1.0.0",
"parms":{"from":{"type":"constant",
"outputCriteria":"test.integer;1.0.0",
"name":"from",
"data":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
}
},
"to":{"type":"constant",
"outputCriteria":"test.integer;1.0.0",
"name":"to",
"data":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
}
},
"base":{"type":"variable",
"outputCriteria":"test.string;1.0.0",
"variableName":"business.a.aa"
}
},
"matchersParms":{"base":{"test.string;1.0.0":{"dataTypeId":"test.string;1.0.0",
"relationship":{"source":"test.string;1.0.0",
"target":"test.string;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
},
"from":{"test.integer;1.0.0":{"dataTypeId":"test.integer;1.0.0",
"relationship":{"source":"test.integer;1.0.0",
"target":"test.integer;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
},
"to":{"test.integer;1.0.0":{"dataTypeId":"test.integer;1.0.0",
"relationship":{"source":"test.integer;1.0.0",
"target":"test.integer;1.0.0",
"path":[],
"targetType":"self"
},
"subMatchers":{},
"reverse":false
}
}
}
},
"variablesMatchers":{},
"variableInfos":{"business___public.a.aa":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"business___public.a.cc":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
},
"business.a.aa":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"business.a.cc":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
},
"element111___public":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"element111":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
},
"index___public":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
},
"index":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
}
}
},
"uiId":"735",
"attribute":"style",
"scriptFunction":function(scriptExpressionData){
	return "color:"+scriptExpressionData["1"];
} 
,
"scriptExpressionScriptFunction":{"1":function(expressionsData, constantsData, variablesData){
	return expressionsData["1_0"].value=='s isfff'?'red':'blue';
} 

}
}],
"scriptExpressionTagAttributes":[],
"uiTags":{"730":{"tagName":"include",
"contextMapping":{},
"tagContext":{"local2Global":{"element111":"element111___public",
"nosliwattribute_source":"nosliwattribute_source___private",
"nosliwattribute_context":"nosliwattribute_context___private",
"nosliwattribute_event":"nosliwattribute_event___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"element111___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"element111":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Basic",
"type":"tag",
"context":{"local2Global":{"element111":"element111___public"
},
"context":{"element":{"element111___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"element111":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[{"uiId":"766",
"event":"valueChanged",
"function":"textInputValueChanged"
}],
"attributes":{"source":"Example_Include_simple",
"context":"",
"event":"changeInputTextIncludeBasic=changeInputTextIncludeBasicMapped",
"nosliwid":"730"
},
"html":"&lt;br nosliwid=&quot;763&quot;&gt;&lt;span&gt; ************************Included: &lt;/span&gt;&lt;br nosliwid=&quot;764&quot;&gt;&lt;span&gt; &lt;/span&gt;&lt;span nosliwid=&quot;762&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;765&quot;&gt;&lt;span&gt; TextInput:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;766-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;766-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;767&quot;&gt;&lt;span&gt; ************************************* &lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;!-- This part can be used to define expressions		--&gt;",
"constants":{},
"events":{"changeInputTextIncludeBasic":{"name":"changeInputTextIncludeBasic",
"description":"",
"info":{},
"data":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
}
},
"commands":{"Include":{"name":"Include",
"description":"",
"info":{},
"parm":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
},
"result":"result"
}
},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(element111)?.value + ' 7777 ' ",
"variableNames":["element111"],
"expressions":{}
}
},
"uiId":"762",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["element111"].value + ' 7777 ' ;
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"766":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"730",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"element111",
"nosliwid":"766"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"eventMapping":{"changeInputTextIncludeBasic":"changeInputTextIncludeBasicMapped"
},
"commandMapping":{},
"serviceMapping":{},
"script":{ textInputValueChanged : function(info, env){ env.trigueEvent("changeInputTextIncludeBasic", info.eventData); }, command_Include : function(data, env){ return data.data + " Include"; }, }
},
"731":{"tagName":"include",
"contextMapping":{"element":"business.a.aa"
},
"tagContext":{"local2Global":{"index":"index___public",
"business":"business___public",
"nosliwattribute_source":"nosliwattribute_source___private",
"nosliwattribute_context":"nosliwattribute_context___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"index___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"business___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"business":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Basic",
"type":"tag",
"context":{"local2Global":{"index":"index___public",
"element":"element___public"
},
"context":{"element":{"index___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"element___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"element":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"source":"Example_Object_Basic_Include",
"context":"element=business.a.aa",
"nosliwid":"731"
},
"html":"&lt;br nosliwid=&quot;778&quot;&gt;&lt;span&gt; ************************Included: &lt;/span&gt;&lt;br nosliwid=&quot;779&quot;&gt;&lt;span&gt; Index: &lt;/span&gt;&lt;span nosliwid=&quot;776&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;780&quot;&gt;&lt;span&gt; TextInput:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;781-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;781-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;782&quot;&gt;&lt;span&gt; &lt;/span&gt;&lt;span nosliwid=&quot;777&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;783&quot;&gt;&lt;span&gt; ************************************* &lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;!--			TextInput:&lt;nosliw-textinput data=&quot;element&quot;/&gt; 			&lt;br&gt;			Index: &lt;%=?(index)?%&gt;  --&gt;   &lt;!-- This part can be used to define expressions		--&gt;",
"constants":{},
"events":{"changeInputTextInclude":{"name":"changeInputTextInclude",
"description":"",
"info":{},
"data":{"element":{"data":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"element___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
}
},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(element)?.value + ' 7777 ' ",
"variableNames":["element"],
"expressions":{}
}
},
"uiId":"777",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["element"].value + ' 7777 ' ;
} 

}
},{"scriptExpressions":{"0":{"definition":"?(index)?.value",
"variableNames":["index"],
"expressions":{}
}
},
"uiId":"776",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["index"].value;
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"781":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"731",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"element",
"nosliwid":"781"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{},
"script":{ }
},
"738":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Basic",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"business.a.aa",
"nosliwid":"738"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
},
"740":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.aa"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Basic",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"business.a.aa",
"nosliwid":"740"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
},
"747":{"tagName":"loop",
"contextMapping":{},
"tagContext":{"local2Global":{"from":"from___public",
"to":"to___public",
"aaaa":"aaaa___public",
"bbbb":"bbbb___public",
"cccc":"cccc___public",
"dddd":"dddd___public",
"ffff":"ffff___public",
"eeee":"eeee___public",
"base":"base___public",
"business":"business___public",
"element111":"element111___public",
"index":"index___protected",
"ele":"ele___protected",
"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_element":"nosliwattribute_element___private",
"nosliwattribute_index":"nosliwattribute_index___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"business___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"default",
"definition":{"type":"node",
"processed":"false",
"child":{"a":{"type":"node",
"processed":"false",
"child":{"aa":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
}
},
"business":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"self",
"definition":{"type":"node",
"processed":"false",
"child":{"a":{"type":"node",
"processed":"false",
"child":{"aa":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
}
},
"element111___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"element111":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"index___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
},
"ele___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.cc.element"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"ele":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"ele___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public",
"path":"a.cc"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
},
"id":"Example_Object_Basic",
"type":"tag",
"context":{"local2Global":{"from":"from___public",
"to":"to___public",
"aaaa":"aaaa___public",
"bbbb":"bbbb___public",
"cccc":"cccc___public",
"dddd":"dddd___public",
"ffff":"ffff___public",
"eeee":"eeee___public",
"base":"base___public",
"business":"business___public",
"element111":"element111___public",
"index":"index___protected",
"ele":"ele___protected"
},
"context":{"element":{"business___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"default",
"definition":{"type":"node",
"processed":"false",
"child":{"a":{"type":"node",
"processed":"false",
"child":{"aa":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
}
},
"business":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"business___public"
},
"parent":"self",
"definition":{"type":"node",
"processed":"false",
"child":{"a":{"type":"node",
"processed":"false",
"child":{"aa":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
},
"cc":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.array;1.0.0%||element:test.string;1.0.0||%",
"info":{}
}
}
}
}
}
}
}
},
"element111___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"element111":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"element111___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"index___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"ele___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"ele___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"ele":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"ele___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"elementEvents":[{"uiId":"752",
"event":"click",
"function":"deleteElementInLoop"
}],
"tagEvents":[],
"attributes":{"data":"business.a.cc",
"element":"ele",
"index":"index",
"nosliwid":"747"
},
"html":"&lt;!--				&lt;nosliw-include source=&quot;Example_Object_Basic_Include&quot; context=&quot;element=ele&quot; /&gt;   --&gt; &lt;br nosliwid=&quot;750&quot;&gt;&lt;span&gt; Index: &lt;/span&gt;&lt;span nosliwid=&quot;748&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;751&quot;&gt;&lt;span&gt; &lt;/span&gt;&lt;span nosliwid=&quot;749&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;a href=&quot;&quot; nosliwid=&quot;752&quot;&gt;&lt;span&gt;Delete&lt;/span&gt;&lt;/a&gt; &lt;br nosliwid=&quot;753&quot;&gt;&lt;span&gt; TextInput:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;754-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;754-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;755&quot;&gt;",
"constants":{"from___public":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
},
"from":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":3
},
"to___public":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
},
"to":{"dataTypeId":"test.integer;1.0.0",
"valueFormat":"JSON",
"value":7
},
"aaaa___public":"18",
"aaaa":"18",
"bbbb___public":"true",
"bbbb":"true",
"cccc___public":{"a":12345,"b":true,"c":"good","d":18},
"cccc":{"a":12345,"b":true,"c":"good","d":18},
"dddd___public":"12351.0",
"dddd":"12351.0",
"ffff___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"LITERATE",
"value":"Thisismyworldabcdef"
},
"ffff":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"LITERATE",
"value":"Thisismyworldabcdef"
},
"eeee___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"sismfff"
},
"eeee":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"sismfff"
},
"base___public":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"This is my world!"
},
"base":{"dataTypeId":"test.string;1.0.0",
"valueFormat":"JSON",
"value":"This is my world!"
}
},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(index)?",
"variableNames":["index"],
"expressions":{}
}
},
"uiId":"748",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["index"];
} 

}
},{"scriptExpressions":{"0":{"definition":"?(ele)?.value + ' 7777 ' ",
"variableNames":["ele"],
"expressions":{}
}
},
"uiId":"749",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["ele"].value + ' 7777 ' ;
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"754":{"tagName":"textinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"ele___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.string;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"747",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"ele",
"nosliwid":"754"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{},
"script":{ deleteElementInLoop : function(data, info){ event.preventDefault(); var node_createContextVariable = nosliw.getNodeData("uidata.context.createContextVariable"); var node_CONSTANT = nosliw.getNodeData("constant.CONSTANT"); var node_requestServiceProcessor = nosliw.getNodeData("request.requestServiceProcessor"); var node_createBatchUIDataOperationRequest = nosliw.getNodeData("uidata.uidataoperation.createBatchUIDataOperationRequest"); var node_UIDataOperation = nosliw.getNodeData("uidata.uidataoperation.UIDataOperation"); var node_uiDataOperationServiceUtility = nosliw.getNodeData("uidata.uidataoperation.uiDataOperationServiceUtility"); var node_createContextVariable = nosliw.getNodeData("uidata.context.createContextVariable"); var node_createServiceRequestInfoSequence = nosliw.getNodeData("request.request.createServiceRequestInfoSequence"); var opRequest = node_createBatchUIDataOperationRequest(this.getContext()); var uiDataOperation = new node_UIDataOperation("ele", node_uiDataOperationServiceUtility.createDeleteOperationService("")); opRequest.addUIDataOperation(uiDataOperation); node_requestServiceProcessor.processRequest(opRequest, false); /* var requestInfo = node_createServiceRequestInfoSequence({}, { success:function(requestInfo, data){ } }); var that = this; requestInfo.addRequest(this.getContext().getDataOperationRequest("index", node_uiDataOperationServiceUtility.createGetOperationService(), { success : function(request, data){ var elePath = data.value; var opRequest = node_createBatchUIDataOperationRequest(that.getContext()); var uiDataOperation = new node_UIDataOperation("ele", node_uiDataOperationServiceUtility.createDeleteOperationService("")); opRequest.addUIDataOperation(uiDataOperation); return opRequest; } })); node_requestServiceProcessor.processRequest(requestInfo, false); */ } }
}
},
"script":{ newElementInLoop : function(data, info, env){ event.preventDefault(); var node_createContextVariable = nosliw.getNodeData("uidata.context.createContextVariable"); var node_CONSTANT = nosliw.getNodeData("constant.CONSTANT"); var node_requestServiceProcessor = nosliw.getNodeData("request.requestServiceProcessor"); var node_createBatchUIDataOperationRequest = nosliw.getNodeData("uidata.uidataoperation.createBatchUIDataOperationRequest"); var node_UIDataOperation = nosliw.getNodeData("uidata.uidataoperation.UIDataOperation"); var node_uiDataOperationServiceUtility = nosliw.getNodeData("uidata.uidataoperation.uiDataOperationServiceUtility"); var node_createContextVariableInfo = nosliw.getNodeData("uidata.context.createContextVariableInfo"); var eleData = { dataTypeId: "test.string;1.0.0", value: "This is my world 33333!" }; var requestInfo = node_createBatchUIDataOperationRequest(this.getContext()); var uiDataOperation = new node_UIDataOperation(node_createContextVariableInfo("business.a.cc"), node_uiDataOperationServiceUtility.createAddElementOperationService("", eleData, 1)); requestInfo.addUIDataOperation(uiDataOperation); node_requestServiceProcessor.processRequest(requestInfo, false); }, textInputValueChanged : function(info, env){ env.trigueEvent("changeInputText", info.eventData); }, command_Start :function(data, env){ return data.data + " Start"; }, }
}, {"loadPattern":"file"
});

