
if(typeof nosliw!='undefined' && nosliw.runtime!=undefined && nosliw.runtime.getResourceService()!=undefined) nosliw.runtime.getResourceService().importResource({"id":{"id":"Page_SoccerForFun_PlayerLineup",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Page_SoccerForFun_PlayerLineup",
"type":"resource",
"context":{"local2Global":{"lineup":"lineup___public"
},
"context":{"element":{"lineup___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"value",
"processed":"true"
},
"defaultValue":{"waitingList":["Peter","David"],"lineUp":[]}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"true"
}
},
"defaultValue":{"waitingList":["Peter","David"],"lineUp":[]}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{},
"html":"&lt;div style=&quot;height:1500px&quot; nosliwid=&quot;801&quot;&gt;  &lt;br nosliwid=&quot;802&quot;&gt; &lt;span&gt; &lt;/span&gt; &lt;span style=&quot;color:green&quot; nosliwid=&quot;803&quot;&gt;&lt;span&gt;&#24403;&#21069;&#38453;&#23481;:&lt;/span&gt;&lt;/span&gt; &lt;span&gt; &lt;/span&gt; &lt;br nosliwid=&quot;804&quot;&gt;  &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;805-tag-start&quot;&gt;&lt;/nosliw&gt; &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;805-tag-end&quot;&gt;&lt;/nosliw&gt;  &lt;br nosliwid=&quot;811&quot;&gt; &lt;span&gt; &lt;/span&gt; &lt;span style=&quot;color:red&quot; nosliwid=&quot;812&quot;&gt;&lt;span&gt;Waiting List:&lt;/span&gt;&lt;/span&gt; &lt;span&gt; &lt;/span&gt; &lt;br nosliwid=&quot;813&quot;&gt;  &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;814-tag-start&quot;&gt;&lt;/nosliw&gt; &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;814-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;/div&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{"lineupService":{"provider":"lineupService",
"name":"lineupService",
"info":{},
"serviceMapping":{"outputMapping":{"success":{"type":"mapping",
"name":"",
"description":"",
"info":{},
"definition":{"name":"",
"description":"",
"info":{},
"association":{"default":{"element":{"lineup":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"false",
"path":{"rootEleName":"lineup",
"path":"value"
},
"parent":"default"
}
}
}
}
}
},
"output":{"default":true
},
"input":{"default":true
},
"association":{"default":{"context":{"element":{"lineup":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup",
"path":"value"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
},
"pathMapping":{"lineup":"default.lineup.value"
},
"flatOutput":true,
"flatInput":{"default":"true"
},
"convertFunction":function(input, utilFunction){

	var output = {};

/*	
	//build element from inherited first
	if(false){
		if({default=true} && true){
			_.each(input, function(ele, name){
				output[name] = ele;
			});
		}
		else if(!{default=true} && !true){
			_.each(input, function(context, categary){
				_.each(context, function(ele, name){
					output[name] = ele;
				});
			});
		}		
		else if(!{default=true} && true){
			_.each(input, function(context, categary){
				_.each(context, function(ele, name){
					output[name] = ele;
					output[name+"___"+categary] = ele;
				});
			});
		}		
		else if({default=true} && !true){
			_.each(input, function(ele, name){
				var segs = name.split("___");
				if(segs.length==2){
					var context = output[segs[1]];
					if(context==undefined){
						context = {};
						output[segs[1]] = context;
					}
					context[segs[0]] = ele;
				}
			});
		}		
	}
*/
	
	//build skeleton first
	if(true){
		_.each({
  "lineup": {}
}, function(value, name){
			output[name] = value;
		});
	}
	else{
		_.each({
  "lineup": {}
}, function(context, categary){
			var context1 = output[categary];
			if(context1==undefined){
				context1 = {};
				output[categary] = context1;
			} 
			_.each(context, function(ele, name){
				context1[name] = ele;
			});
		});
	}
	
	//asign mapped element, leaf data
	output = utilFunction(output, ["lineup"], input, ["default","lineup","value"]);

	
	return output;
}

}
}
}
},
"inputMapping":{"type":"mapping",
"name":"",
"description":"",
"info":{},
"definition":{"name":"",
"description":"",
"info":{},
"association":{}
},
"output":{},
"input":{},
"association":{}
},
"task":""
}
}
},
"serviceProviders":{"lineupService":{"name":"lineupService",
"description":"",
"info":{},
"serviceId":"lineupService",
"serviceInterface":{"parm":{},
"result":{"success":{"name":"success",
"description":"",
"info":{},
"output":{"lineup":{"name":"",
"description":"",
"info":{},
"criteria":"test.data;1.0.0"
}
}
}
}
}
}
},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"805":{"tagName":"loop",
"contextMapping":{},
"tagContext":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"spot":"spot___protected",
"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_element":"nosliwattribute_element___private",
"nosliwattribute_index":"nosliwattribute_index___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"spot___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public",
"path":"lineUp.element"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public",
"path":"lineUp"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"id":"Page_SoccerForFun_PlayerLineup",
"type":"tag",
"context":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"spot":"spot___protected"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"spot___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"lineup.lineUp",
"element":"spot",
"index":"index",
"nosliwid":"805"
},
"html":"&lt;span&gt; &lt;/span&gt;&lt;span nosliwid=&quot;806&quot;&gt;&lt;/span&gt;&lt;span&gt;.&amp;nbsp; &lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;807-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;807-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;810&quot;&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(index)?+1",
"variableNames":["index"],
"expressions":{}
}
},
"uiId":"806",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["index"]+1;
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"807":{"tagName":"loop",
"contextMapping":{},
"tagContext":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"player":"player___protected",
"spot":"spot___protected",
"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_element":"nosliwattribute_element___private",
"nosliwattribute_index":"nosliwattribute_index___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"player___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected",
"path":"players.element"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"player":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"player___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected",
"path":"players"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"id":"805",
"type":"tag",
"context":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"player":"player___protected",
"spot":"spot___protected"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"player___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"player___protected"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"player":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"player___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"spot.players",
"element":"player",
"index":"index",
"nosliwid":"807"
},
"html":"&lt;span&gt; &lt;/span&gt;&lt;span style=&quot;display:inline-block;width:140px;min-width:140px;max-width:140px;&quot; nosliwid=&quot;808&quot;&gt;&lt;span nosliwid=&quot;809&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(player)?",
"variableNames":["player"],
"expressions":{}
}
},
"uiId":"809",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["player"];
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
},
"814":{"tagName":"loop",
"contextMapping":{},
"tagContext":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"spot":"spot___protected",
"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_element":"nosliwattribute_element___private",
"nosliwattribute_index":"nosliwattribute_index___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"spot___protected":{"name":"",
"description":"",
"info":{"instantiate":"manual"
},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public",
"path":"waitingList.element"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public",
"path":"waitingList"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"id":"Page_SoccerForFun_PlayerLineup",
"type":"tag",
"context":{"local2Global":{"lineup":"lineup___public",
"index":"index___protected",
"spot":"spot___protected"
},
"context":{"element":{"lineup___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"lineup":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"lineup___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"index___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"index":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"index___protected"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.integer;1.0.0",
"info":{}
}
}
}
},
"spot___protected":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"spot":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"spot___protected"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"lineup.waitingList",
"element":"spot",
"index":"index",
"nosliwid":"814"
},
"html":"&lt;span&gt; &lt;/span&gt;&lt;span nosliwid=&quot;815&quot;&gt;&lt;/span&gt;&lt;span&gt;.&amp;nbsp; &lt;/span&gt;&lt;span nosliwid=&quot;816&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;br nosliwid=&quot;817&quot;&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(index)?",
"variableNames":["index"],
"expressions":{}
}
},
"uiId":"815",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["index"];
} 

}
},{"scriptExpressions":{"0":{"definition":"?(spot)?",
"variableNames":["spot"],
"expressions":{}
}
},
"uiId":"816",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["spot"];
} 

}
}],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"script":{ command_updateData : function(data, request, env){ var node_createContextVariable = nosliw.getNodeData("uidata.context.createContextVariable"); var node_CONSTANT = nosliw.getNodeData("constant.CONSTANT"); var node_requestServiceProcessor = nosliw.getNodeData("request.requestServiceProcessor"); var node_createBatchUIDataOperationRequest = nosliw.getNodeData("uidata.uidataoperation.createBatchUIDataOperationRequest"); var node_UIDataOperation = nosliw.getNodeData("uidata.uidataoperation.UIDataOperation"); var node_uiDataOperationServiceUtility = nosliw.getNodeData("uidata.uidataoperation.uiDataOperationServiceUtility"); var node_createContextVariableInfo = nosliw.getNodeData("uidata.context.createContextVariableInfo"); var requestInfo = env.getServiceRequest("lineupService", { success : function(request){ } }); node_requestServiceProcessor.processRequest(requestInfo, false); }, }
}, {"loadPattern":"file"
});

