
if(typeof nosliw!='undefined' && nosliw.runtime!=undefined && nosliw.runtime.getResourceService()!=undefined) nosliw.runtime.getResourceService().importResource({"id":{"id":"Decoration_setting_framework7",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Decoration_setting_framework7",
"type":"resource",
"context":{"local2Global":{"nosliw_module_setting_name":"nosliw_module_setting_name___public",
"nosliw_module_setting_persist":"nosliw_module_setting_persist___public",
"nosliw_module_setting_modified":"nosliw_module_setting_modified___public"
},
"context":{"element":{"nosliw_module_setting_name___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"value",
"processed":"true"
},
"defaultValue":""
},
"nosliw_module_setting_name":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_name___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"true"
}
},
"defaultValue":""
},
"nosliw_module_setting_persist___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"value",
"processed":"true"
},
"defaultValue":true
},
"nosliw_module_setting_persist":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_persist___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"true"
}
},
"defaultValue":true
},
"nosliw_module_setting_modified___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"value",
"processed":"true"
},
"defaultValue":true
},
"nosliw_module_setting_modified":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_modified___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"true"
}
},
"defaultValue":true
}
}
}
},
"elementEvents":[{"uiId":"962",
"event":"click",
"function":"new"
},{"uiId":"964",
"event":"click",
"function":"save"
},{"uiId":"961",
"event":"click",
"function":"submit"
},{"uiId":"963",
"event":"click",
"function":"delete"
}],
"tagEvents":[],
"attributes":{"nosliwattribute_placeholder":"id:pleaseEmbed"
},
"html":"&lt;br nosliwid=&quot;959&quot;&gt;&lt;span&gt; SettingName : &lt;/span&gt;&lt;span nosliwid=&quot;958&quot;&gt;&lt;/span&gt;&lt;span&gt; &lt;/span&gt;&lt;div nosliwid=&quot;960&quot;&gt;  &lt;a href=&quot;&quot; nosliwid=&quot;961&quot;&gt;&lt;span&gt;Submit&lt;/span&gt;&lt;/a&gt;  &lt;a href=&quot;&quot; nosliwid=&quot;962&quot;&gt;&lt;span&gt;New&lt;/span&gt;&lt;/a&gt;  &lt;a href=&quot;&quot; style=&quot;&quot; nosliwid=&quot;963&quot;&gt;&lt;span&gt;Delete&lt;/span&gt;&lt;/a&gt;  &lt;a href=&quot;&quot; style=&quot;&quot; nosliwid=&quot;964&quot;&gt;&lt;span&gt;Save&lt;/span&gt;&lt;/a&gt; &lt;/div&gt; &lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;965-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;965-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;div id=&quot;pleaseEmbed&quot; nosliwid=&quot;966&quot;&gt;&lt;/div&gt; &lt;br nosliwid=&quot;967&quot;&gt;",
"constants":{},
"events":{"submit":{"name":"submit",
"description":"",
"info":{},
"data":{"element":{}
}
}
},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[{"scriptExpressions":{"0":{"definition":"?(nosliw_module_setting_name)?",
"variableNames":["nosliw_module_setting_name"],
"expressions":{}
}
},
"uiId":"958",
"scriptFunction":function(scriptExpressionData){
	return scriptExpressionData["0"];
} 
,
"scriptExpressionScriptFunction":{"0":function(expressionsData, constantsData, variablesData){
	return variablesData["nosliw_module_setting_name"];
} 

}
}],
"scriptExpressionInAttributes":[{"scriptExpressions":{"1":{"definition":"(!?(nosliw_module_setting_persist)?)||?(nosliw_module_setting_modified)?==true?'inline':'none'",
"variableNames":["nosliw_module_setting_persist","nosliw_module_setting_modified"],
"expressions":{}
}
},
"uiId":"964",
"attribute":"style",
"scriptFunction":function(scriptExpressionData){
	return "display:"+scriptExpressionData["1"];
} 
,
"scriptExpressionScriptFunction":{"1":function(expressionsData, constantsData, variablesData){
	return (!variablesData["nosliw_module_setting_persist"])||variablesData["nosliw_module_setting_modified"]==true?'inline':'none';
} 

}
},{"scriptExpressions":{"1":{"definition":"?(nosliw_module_setting_persist)?==true?'inline':'none'",
"variableNames":["nosliw_module_setting_persist"],
"expressions":{}
}
},
"uiId":"963",
"attribute":"style",
"scriptFunction":function(scriptExpressionData){
	return "display:"+scriptExpressionData["1"];
} 
,
"scriptExpressionScriptFunction":{"1":function(expressionsData, constantsData, variablesData){
	return variablesData["nosliw_module_setting_persist"]==true?'inline':'none';
} 

}
}],
"scriptExpressionTagAttributes":[],
"uiTags":{"965":{"tagName":"contextvalue",
"contextMapping":{},
"tagContext":{"local2Global":{"nosliw_module_setting_name":"nosliw_module_setting_name___public",
"nosliw_module_setting_persist":"nosliw_module_setting_persist___public",
"nosliw_module_setting_modified":"nosliw_module_setting_modified___public",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"nosliw_module_setting_name___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_name___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_name":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_name___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_persist___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_persist___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_persist":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_persist___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_modified___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_modified___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_modified":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_modified___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"id":"Decoration_setting_framework7",
"type":"tag",
"context":{"local2Global":{"nosliw_module_setting_name":"nosliw_module_setting_name___public",
"nosliw_module_setting_persist":"nosliw_module_setting_persist___public",
"nosliw_module_setting_modified":"nosliw_module_setting_modified___public"
},
"context":{"element":{"nosliw_module_setting_name___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_name___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_name":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_name___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_persist___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_persist___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_persist":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_persist___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_modified___public":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_modified___public"
},
"parent":"default",
"definition":{"type":"value",
"processed":"false"
}
}
},
"nosliw_module_setting_modified":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"nosliw_module_setting_modified___public"
},
"parent":"self",
"definition":{"type":"value",
"processed":"false"
}
}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"nosliwid":"965"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
},
"script":{ submit : function(info, env){ event.preventDefault(); env.trigueEvent("nosliw_module_setting_submitSetting", info.eventData); }, new : function(info, env){ event.preventDefault(); env.trigueEvent("nosliw_module_setting_newSetting", info.eventData); }, delete : function(info, env){ event.preventDefault(); env.trigueEvent("nosliw_module_setting_deleteSetting", info.eventData); }, save : function(info, env){ event.preventDefault(); env.trigueEvent("nosliw_module_setting_saveSetting", info.eventData); }, }
}, {"loadPattern":"file"
});

