
if(typeof nosliw!='undefined' && nosliw.runtime!=undefined && nosliw.runtime.getResourceService()!=undefined) nosliw.runtime.getResourceService().importResource({"id":{"id":"Page_MySchool_Query",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Page_MySchool_Query",
"type":"resource",
"context":{"local2Global":{"schoolType":"schoolType___public",
"schoolRating":"schoolRating___public"
},
"context":{"element":{"schoolType___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.options;1.0.0",
"info":{}
}
},
"defaultValue":{"dataTypeId":"test.options;1.0.0","value":{"optionsId":"schoolType","value":"Public"}}
},
"schoolType":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"schoolType___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.options;1.0.0",
"info":{}
}
}
},
"defaultValue":{"dataTypeId":"test.options;1.0.0","value":{"optionsId":"schoolType","value":"Public"}}
},
"schoolRating___public":{"name":"",
"description":"",
"info":{},
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.float;1.0.0",
"info":{}
}
},
"defaultValue":{"dataTypeId":"test.float;1.0.0","value":9}
},
"schoolRating":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"schoolRating___public"
},
"parent":"self",
"definition":{"type":"data",
"processed":"true",
"criteria":{"status":"close",
"criteria":"test.float;1.0.0",
"info":{}
}
}
},
"defaultValue":{"dataTypeId":"test.float;1.0.0","value":9}
}
}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{},
"html":"&lt;br nosliwid=&quot;201&quot;&gt; &lt;br nosliwid=&quot;202&quot;&gt;&lt;span&gt; SchoolRating:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;203-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;203-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;204&quot;&gt; &lt;br nosliwid=&quot;205&quot;&gt;&lt;span&gt; SchoolType:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;206-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;206-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;207&quot;&gt;",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{"203":{"tagName":"floatinput",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"schoolRating___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.float;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.float;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Page_MySchool_Query",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"data":"schoolRating",
"nosliwid":"203"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
},
"206":{"tagName":"options",
"contextMapping":{},
"tagContext":{"local2Global":{"internal_data":"internal_data___private",
"nosliwattribute_id":"nosliwattribute_id___private",
"nosliwattribute_data":"nosliwattribute_data___private",
"nosliwattribute_nosliwid":"nosliwattribute_nosliwid___private"
},
"context":{"element":{"internal_data___private":{"name":"",
"description":"",
"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"schoolType___public"
},
"parent":"default",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.options;1.0.0",
"info":{}
}
}
}
},
"internal_data":{"info":{},
"definition":{"type":"relative",
"processed":"true",
"path":{"rootEleName":"internal_data___private"
},
"parent":"self",
"definition":{"type":"data",
"processed":"false",
"criteria":{"status":"close",
"criteria":"test.options;1.0.0",
"info":{}
}
}
}
}
}
}
},
"id":"Page_MySchool_Query",
"type":"tag",
"context":{"local2Global":{},
"context":{"element":{}
}
},
"elementEvents":[],
"tagEvents":[],
"attributes":{"id":"schoolType",
"data":"schoolType",
"nosliwid":"206"
},
"html":"",
"constants":{},
"events":{},
"commands":{},
"services":{},
"serviceProviders":{},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"uiTags":{},
"eventMapping":{},
"commandMapping":{},
"serviceMapping":{}
}
}
}, {"loadPattern":"file"
});

