/* Generated By:JavaCC: Do not edit this line. NosliwExpressionParserTreeConstants.java Version 6.0_1 */
package com.nosliw.expression.parser;

public interface NosliwExpressionParserTreeConstants
{
  public int JJTNAME = 0;
  public int JJTCONSTANT = 1;
  public int JJTDATATYPE = 2;
  public int JJTVARIABLE = 3;
  public int JJTEXPRESSION = 4;
  public int JJTEXPRESSION1 = 5;


  public String[] jjtNodeName = {
    "Name",
    "CONSTANT",
    "DATATYPE",
    "VARIABLE",
    "EXPRESSION",
    "EXPRESSION1",
  };
}
/* JavaCC - OriginalChecksum=680b9984cacb0e84c2b64a024f0d5e4b (do not edit this line) */
