
nosliw.runtime.getResourceService().importResource({"id":{"id":"Example_App_Query_School_mobile",
"type":"uiResource"
},
"children":[],
"dependency":{},
"info":{}
}, {"id":"Example_App_Query_School_mobile",
"type":"resource",
"context":{"public":{"schoolType":{"children":{},
"definition":"test.options;1.0.0",
"type":"absolute",
"default":{"dataTypeId":"test.options;1.0.0","value":{"optionsId":"schoolType","value":"Public"}}
},
"schoolRating":{"children":{},
"definition":"test.float;1.0.0",
"type":"absolute",
"default":{"schoolRating":{"dataTypeId":"test.float;1.0.0","value":9}}
}
},
"internal":{},
"private":{},
"excluded":{}
},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"elementEvents":[],
"tagEvents":[],
"uiTags":{"276":{"id":"276",
"type":"tag",
"context":{"public":{},
"internal":{},
"private":{"internal_data":{"children":{},
"definition":"test.float;1.0.0",
"path":{"rootEleName":"schoolRating"
},
"type":"relative"
}
},
"excluded":{}
},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"elementEvents":[],
"tagEvents":[],
"uiTags":{},
"attributes":{"data":"schoolRating",
"nosliwid":"276"
},
"html":"",
"constants":{},
"tagName":"floatinput"
},
"279":{"id":"279",
"type":"tag",
"context":{"public":{},
"internal":{},
"private":{"internal_data":{"children":{},
"definition":"test.options;1.0.0",
"path":{"rootEleName":"schoolType"
},
"type":"relative"
}
},
"excluded":{}
},
"scriptExpressionsInContent":[],
"scriptExpressionInAttributes":[],
"scriptExpressionTagAttributes":[],
"elementEvents":[],
"tagEvents":[],
"uiTags":{},
"attributes":{"id":"schoolType",
"data":"schoolType",
"nosliwid":"279"
},
"html":"",
"constants":{},
"tagName":"options"
}
},
"attributes":{},
"html":"&lt;br nosliwid=&quot;275&quot;&gt;&lt;span&gt; SchoolRating:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;276-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;276-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;277&quot;&gt; &lt;br nosliwid=&quot;278&quot;&gt;&lt;span&gt; SchoolType:&lt;/span&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;279-tag-start&quot;&gt;&lt;/nosliw&gt;&lt;nosliw style=&quot;display:none;&quot; nosliwid=&quot;279-tag-end&quot;&gt;&lt;/nosliw&gt; &lt;br nosliwid=&quot;280&quot;&gt;     &lt;!-- This part can be used to define expressions		--&gt;",
"constants":{},
"script":{
	
	}
}, {"loadPattern":"file"
});

